front_search:
    resource: "@FrontBundle/Resources/config/routing/search.yml"
    prefix:   /search

front_profile:
    resource: "@FrontBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

front_city:
    resource: "@FrontBundle/Resources/config/routing/city.yml"
    prefix:   /city

front_category:
    resource: "@FrontBundle/Resources/config/routing/category.yml"
    prefix:   /category

front_advertfile:
    resource: "@FrontBundle/Resources/config/routing/advertfile.yml"
    prefix:   /advertfile

front_advert:
    resource: "@FrontBundle/Resources/config/routing/advert.yml"
    prefix:   /annonce

front_whishlist:
    resource: "@FrontBundle/Resources/config/routing/whishlist.yml"
    prefix:   /whishlist

front_user:
    resource: "@FrontBundle/Resources/config/routing/user.yml"
    prefix:   /user

front_homepage_page:
    path:     /{page}
    defaults: { _controller: FrontBundle:Default:index, page: 1 }
    requirements:
        page: \d+

front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

