front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"