# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern: ^/back
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                failure_path:   null
                default_target_path: back_homepage
            logout:
                path: fos_user_security_logout
                target: front_homepage
            anonymous:    true

        # defaut login area for standard users
        main:
            context: primary_auth
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: front_homepage
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /login
                use_forward: false
                failure_path: /login
                default_target_path: front_homepage
                oauth_user_provider:
                    service: my_user_provider
#            oauth:
#                resource_owners:
#                    facebook:           "/connect/check-facebook"
#                    google:             "/connect/check-google"
#                login_path:        /connect
#                failure_path:      /connect
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
            logout:
                path: fos_user_security_logout
                target: front_homepage
            anonymous:    true

    access_control:
        # front
        - { path: ^/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/annonce/logged-*/*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/annonce/logged-*/*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_FULLY }

        #back-office
        - { path: ^/back, role: ROLE_ADMIN }

