# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login area for backoffice users
        #backoffice:
            #context: primary_auth
            #pattern: ^/back
            #form_login:
                #provider:       fos_userbundle
                #login_path:     back_security_login
                #use_forward:    true
                #use_referer:    true
                #check_path:     back_security_check
                #failure_path:   null
                #default_target_path: back_homepage
            #logout:
                #path: back_security_logout
                #target: front_homepage
            #anonymous:    true

        # defaut login area for standard users
        main:
            context: primary_auth
            pattern:            ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: fos_user_profile_show
            logout:
                path: fos_user_security_logout
                target: front_homepage
            anonymous:    true

    access_control:
        # front
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_FULLY }
        # back-office
        - { path: ^/back/, role: ROLE_ADMIN }
