<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * COMMUNS METHODS
     */

    /**
     * FRONTEND METHODS
     */

    /**
     * FRONTEND METHODS
     */

    public function getListCategoryBySlugWithAdvertsOnFrontend($slug)
    {

        $q = $this->createQueryBuilder('c')
            ->select('c, a, f , t')
            ->leftJoin('c.adverts','a')
            ->leftJoin('a.fileadverts', 'f')
            ->leftJoin('a.tags', 't')
            ->where('c.slug = :slug')
            ->andWhere('a.isPublic = 1')
            ->andWhere('a.expiredAt > :date')
            ->andWhere('a.isActivated = 1')
            ->orderBy('a.expiredAt', 'DESC')
            ->orderBy('c.createdAt', 'DESC')
            ->setParameter('slug', $slug)
            ->setParameter('date', date('Y-m-d H:i:s', time()))
        ;

        return $q->getQuery()->getResult();
    }



    /**
     * BACKEND METHODS
     */



}
