<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function findCitiesByNameOrZipcode($term)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.cityName LIKE :term')
            ->orWhere('c.cityZipcode LIKE :term')
            ->setParameter('term', '%'.$term.'%')
            ->orderBy('c.cityName', 'ASC');
        ;
        return $qb->getQuery()->getResult();
    }

    public function findOneCityByNameOrZipcode($city_name,$zipcode)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.cityName = :name')
            ->andWhere('c.cityZipcode = :zipcode')
            ->setParameter('name', $city_name)
            ->setParameter('zipcode', $zipcode);
        ;
        try {
            return $qb->getQuery()->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }

}