<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Return user profile avatar as array
     *
     * @return User
     */
    public function findAllUsersProfileAvatar()
    {
        $q = $this->createQueryBuilder('u')
            ->select('u, p, a')
            ->join('u.profile', 'p')
            ->join('u.avatar', 'a')
            ->getQuery();

        return $q->getResult();
    }

    public function countFullUsers()
    {
        $q = $this->createQueryBuilder('u')
            ->select('COUNT(u) as nbUsers')
            ->getQuery()
        ;

        return $q->getSingleScalarResult();
    }
    public function getListUsers($page = 1, $maxperpage = 12)
    {
        $q = $this->createQueryBuilder('u')
            ->orderBy('u.createdAt', 'DESC')
        ;

        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }
}