<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Return user profile avatar as array
     *
     * @return User
     */
    public function findAllUsersProfileAvatar()
    {
        $q = $this->createQueryBuilder('u')
            ->select('u, p, a')
            ->join('u.profile', 'p')
            ->join('u.avatar', 'a')
            ->getQuery();

        return $q->getResult();
    }
}