back_advert_index:
    path:     /{page}
    defaults: { _controller: "BackBundle:Advert:index", page: 1 }
    requirements:
        page: \d+

back_advert_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Advert:show" }
    methods:  GET

back_advert_new:
    path:     /new
    defaults: { _controller: "BackBundle:Advert:new" }
    methods:  [GET, POST]

back_advert_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Advert:edit" }
    methods:  [GET, POST]

back_advert_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Advert:delete" }
    methods:  DELETE