back_category_index:
    path:     /{page}
    defaults: { _controller: "BackBundle:Category:index", page: 1 }
    methods:  GET
    requirements:
        page: \d+

#back_category_index:
#    path:     /{page}
#    defaults: { _controller: "BackBundle:Category:index", page: 1 }
#    methods:  GET

back_category_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Category:show" }
    methods:  GET

back_category_new:
    path:     /new
    defaults: { _controller: "BackBundle:Category:new" }
    methods:  [GET, POST]

back_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Category:edit" }
    methods:  [GET, POST]

back_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Category:delete" }
    methods:  DELETE
