back_tag_index:
    path:     /
    defaults: { _controller: "BackBundle:Tag:index" }
    methods:  GET

back_tag_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Tag:show" }
    methods:  GET

back_tag_new:
    path:     /new
    defaults: { _controller: "BackBundle:Tag:new" }
    methods:  [GET, POST]

back_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Tag:edit" }
    methods:  [GET, POST]

back_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Tag:delete" }
    methods:  DELETE
