back_whishlist_page:
    path:     /{page}
    defaults: { _controller: "BackBundle:Whishlist:index", page: 1 }
    requirements:
        page: \d+

back_whishlist_index:
    path:     /
    defaults: { _controller: "BackBundle:Whishlist:index", page: 1 }
    methods:  GET

back_whishlist_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Whishlist:show" }
    methods:  GET

back_whishlist_new:
    path:     /new
    defaults: { _controller: "BackBundle:Whishlist:new" }
    methods:  [GET, POST]

back_whishlist_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Whishlist:edit" }
    methods:  [GET, POST]

back_whishlist_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Whishlist:delete" }
    methods:  DELETE
