services:
#     sfc_user.login_listener:
#        class: MainBundle\Listener\LoginListener
#        arguments: [@doctrine.orm.entity_manager]
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    #HWIOAUTHBUNDLE
#    hwi_oauth.user.provider.entity:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
#    my_user_provider:
#        class: MainBundle\Security\Core\User\FOSUBUserProvider
#        #this is the place where the properties are passed to the UserProvider - see config.yml
#        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
#
#    app.provider.oauth:
#        class: MainBundle\Security\Core\User\OAuthUserProvider
#        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
#    athome.registration.form.type:
#        class: FrontBundle\Form\Type\RegistrationFormType
#        arguments: [%fos_user.model.user.class%,"@doctrine.orm.entity_manager"]
#        tags:
#            - { name: form.type, alias: athome_user_registration }

    my_user_provider:
        class: MainBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id},@request_stack]

#    athome.registration.form.handler:
#        class: MainBundle\Form\Handler\RegistrationFormHandler
#        arguments: [@fos_user.registration.form,@request,@fos_user.user_manager,@fos_user.mailer,@fos_user.util.token_generator,@doctrine.orm.entity_manager,@event_dispatcher]
#        scope: request
#        public: false
#    athome.users.listener.user_listener:
#        class: MainBundle\Listener\UserListener
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - { name: kernel.event_listener, event: user.create, method: onUserCreate }
#            - { name: kernel.event_listener, event: user.connect, method: onUserConnect }